// Missouri Learning Standards, science, grades 6-12: the store's
// catalogue, one entry per band and strand (Jay, 2026-09-18: one store
// item per subject and grade band, so a teacher adds only what they
// teach and the browse and suggestion lists stay short).
//
// Text is the Missouri Department of Elementary and Secondary
// Education's 2016 Grade-Level Expectations, copied verbatim from
// https://dese.mo.gov/media/pdf/curr-mls-standards-sci-6-12-sboe-2016
// (extracted 2026-09-18 with the parse in the standards session's
// scratchpad; a handful of entries were trimmed by hand where a page
// break had run sidebar text into them). `note` is the standard's own
// Clarification Statement, minus the label. Middle school is one item
// with every strand, since Missouri writes 6-8 as one band and most
// middle schools teach it integrated.
//
// Ids are the store's SKUs: keep them stable, a teacher's ownership
// record points at them.

export const MISSOURI_SCIENCE_FRAMEWORKS = [
  {
    id: "mo-sci-9-12-ps",
    label: "Missouri Learning Standards · Science 9-12 · Physical",
    short: "MLS",
    blurb: "Missouri's high school physical science expectations: matter and reactions (PS1), forces and motion (PS2), energy (PS3), waves (PS4). Chemistry and physics.",
    source: "https://dese.mo.gov/media/pdf/curr-mls-standards-sci-6-12-sboe-2016",
    standards: [
      { code: "9-12.PS1.A.1", text: "Use the organization of the periodic table to predict the relative properties of elements based on the patterns of electrons in the outermost energy level of atoms.",
        note: "Examples of properties that could be predicted from patterns could include reactivity of metals, types of bonds formed, numbers of bonds formed, and reactions with oxygen." },
      { code: "9-12.PS1.A.2", text: "Construct and revise an explanation for the products of a simple chemical reaction based on the outermost electron states of atoms, trends in the periodic table, and knowledge of the patterns of chemical properties.",
        note: "Examples of chemical reactions could include the reaction of sodium and chlorine, or of oxygen and hydrogen." },
      { code: "9-12.PS1.A.3", text: "Plan and conduct an investigation to gather evidence to compare physical and chemical properties of substances such as melting point, boiling point, vapor pressure, surface tension, and chemical reactivity to infer the relative strength of attractive forces between particles.",
        note: "Emphasis is on understanding the relative strengths of forces between particles. Examples of particles could include ions, atoms, molecules, and networked materials (such as graphite)." },
      { code: "9-12.PS1.A.4", text: "Apply the concepts of bonding and crystalline/molecular structure to explain the macroscopic properties of various categories of structural materials, i.e. metals, ionic (ceramics), and polymers.",
        note: "Emphasis is on the attractive and repulsive forces that determine the functioning of the material. Examples could include why electrically conductive materials are often made of metal, flexible but durable materials are made up of long chained molecules, and pharmaceuticals are designed to interact with specific receptors." },
      { code: "9-12.PS1.A.5", text: "Develop a model to illustrate that the release or absorption of energy from a chemical reaction system depends upon the changes in total bond energy.",
        note: "Emphasis is on the idea that a chemical reaction is a system that affects the energy change. Examples of models could include molecular-level drawings and diagrams of reactions, graphs showing the relative energies of reactants and products, and representations showing energy is conserved." },
      { code: "9-12.PS1.B.1", text: "Apply scientific principles and evidence to provide an explanation about the effects of changing the temperature or concentration of the reacting particles on the rate at which a reaction occurs.",
        note: "Emphasis is on student reasoning that focuses on the number and energy of collisions between molecules." },
      { code: "9-12.PS1.B.2", text: "Refine the design of a chemical system by specifying a change in conditions that would alter the amount of products at equilibrium.",
        note: "Emphasis is on the application of Le Chatelier's Principle and on refining designs of chemical reaction systems, including descriptions of the connection between changes made at the macroscopic level and what happens at the molecular level. Examples of designs could include different ways to increase product formation including adding reactants or removing products." },
      { code: "9-12.PS1.B.3", text: "Use symbolic representations and mathematical calculations to support the claim that atoms, and therefore mass, are conserved during a chemical reaction.",
        note: "Emphasis is on conservation of matter and mass through balanced chemical equations, use of the mole concept and proportional relationships." },
      { code: "9-12.PS1.C.1", text: "Use symbolic representations to illustrate the changes in the composition of the nucleus of the atom and the energy released during the processes of fission, fusion, and radioactive decay.",
        note: "Emphasis is on simple qualitative models, such as pictures or diagrams, and on the scale of energy released in nuclear processes relative to other kinds of transformations." },
      { code: "9-12.PS2.A.1", text: "Analyze data to support and verify the concepts expressed by Newton's 2nd law of motion, as it describes the mathematical relationship among the net force on a macroscopic object, its mass, and its acceleration.",
        note: "Examples of data could include tables or graphs of position or velocity as a function of time for objects subject to a net unbalanced force, such as a falling object, an object rolling down a ramp, or a moving object being pulled by a constant force." },
      { code: "9-12.PS2.A.2", text: "Use mathematical representations to support and verify the concepts that the total momentum of a system of objects is conserved when there is no net force on the system.",
        note: "Emphasis is on the quantitative conservation of momentum in interactions and the qualitative meaning of this principle." },
      { code: "9-12.PS2.A.3", text: "Apply scientific principles of motion and momentum to design, evaluate, and refine a device that minimizes the force on a macroscopic object during a collision.",
        note: "Examples of evaluation and refinement could include determining the success of the device at protecting an object from damage and modifying the design to improve it. Examples of a device could include a football helmet or a parachute." },
      { code: "9-12.PS2.B.1", text: "Use mathematical representations of Newton's Law of Gravitation to describe and predict the gravitational forces between objects.",
        note: "Emphasis is on both quantitative and conceptual descriptions of gravitational fields." },
      { code: "9-12.PS2.B.2", text: "Plan and conduct an investigation to provide evidence that an electric current can produce a magnetic field and that a changing magnetic field can produce an electric current.",
        note: "" },
      { code: "9-12.PS3.A.1", text: "Create a computational model to calculate the change in the energy of one component in a system when the changes in energy are known.",
        note: "Emphasis is on explaining the meaning of mathematical expressions used in the model." },
      { code: "9-12.PS3.A.2", text: "Develop and use models to illustrate that energy at the macroscopic scale can be accounted for as a combination of energy associated with the motions of particles (objects) and energy associated with the relative position of particles (objects).",
        note: "Examples of phenomena at the macroscopic scale could include the conversion of kinetic energy to thermal energy, the energy stored due to position of an object above the earth, and the energy stored between two electrically-charged plates. Examples of models could include diagrams, drawings, descriptions, and computer simulations." },
      { code: "9-12.PS3.A.3", text: "Design, build, and refine a device that works within given constraints to convert one form of energy into another form of energy.",
        note: "Emphasis is on both qualitative and quantitative evaluations of devices. Examples of devices could include Rube Goldberg devices, wind turbines, solar cells, solar ovens, and generators. Examples of constraints could include use of renewable energy forms and efficiency." },
      { code: "9-12.PS3.B.1", text: "Plan and conduct an investigation to provide evidence that the transfer of thermal energy when two components of different temperature are combined within a closed system results in a more uniform energy distribution among the components in the system (second law of thermodynamics).",
        note: "Emphasis is on analyzing data from student investigations and using mathematical thinking to describe the energy changes both quantitatively and conceptually. Examples of investigations could include mixing liquids at different initial temperatures or adding objects at different temperatures to water." },
      { code: "9-12.PS3.C.1", text: "Develop and use a model of two objects interacting through electric or magnetic fields to illustrate the forces between objects and the changes in energy of the objects due to the interaction.",
        note: "Examples of models could include drawings, diagrams, and texts, such as drawings of what happens when two charges of opposite polarity are near each other." },
      { code: "9-12.PS4.A.1", text: "Use mathematical representations to support a claim regarding relationships among the frequency, wavelength, and speed of waves traveling in various media.",
        note: "Examples of data could include electromagnetic radiation traveling in a vacuum and glass, sound waves traveling through air and water, and seismic waves traveling through the Earth." },
      { code: "9-12.PS4.A.2", text: "Evaluate the claims, evidence, and reasoning behind the idea that electromagnetic radiation can be described either by a wave model or a particle model, and that for some situations one model is more useful than the other.",
        note: "Emphasis is on how the experimental evidence supports the claim and how a theory is generally modified in light of new evidence. Examples of a phenomenon could include resonance, interference, diffraction, and photoelectric effect." },
      { code: "9-12.PS4.B.1", text: "Communicate technical information about how electromagnetic radiation interacts with matter.",
        note: "Examples could include solar cells capturing light and converting it to electricity; medical imaging; and communications technology." },
      { code: "9-12.PS4.B.2", text: "Evaluate the validity and reliability of claims in published materials of the effects that different frequencies of electromagnetic radiation have when absorbed by matter.",
        note: "Emphasis is on the idea that photons associated with different frequencies of light have different energies, and the damage to living tissue from electromagnetic radiation depends on the energy of the radiation. Examples of published materials could include trade books, magazines, web resources, videos, and other passages that may reflect bias." },
    ],
  },
  {
    id: "mo-sci-9-12-ls",
    label: "Missouri Learning Standards · Science 9-12 · Life",
    short: "MLS",
    blurb: "Missouri's high school life science expectations: cells and organisms (LS1), ecosystems (LS2), heredity (LS3), evolution (LS4). Biology.",
    source: "https://dese.mo.gov/media/pdf/curr-mls-standards-sci-6-12-sboe-2016",
    standards: [
      { code: "9-12.LS1.A.1", text: "Construct a model of how the structure of DNA determines the structure of proteins which carry out the essential functions of life through systems of specialized cells.",
        note: "Genes are the regions in DNA that code for proteins. Basic transcription and translation explain the roles of DNA and RNA in coding the instructions for making polypeptides." },
      { code: "9-12.LS1.A.2", text: "Develop and use a model to illustrate the hierarchical organization of interacting systems that provide specific functions within multicellular organisms.",
        note: "Emphasis is on functions at the organism system level such as nutrient uptake, water delivery, and organism movement in response to stimuli." },
      { code: "9-12.LS1.A.3", text: "Plan and conduct an investigation to provide evidence that feedback mechanisms maintain homeostasis.",
        note: "Examples of investigations could include heart rate response to exercise, stomata response to moisture and temperature, and root development in response to water levels." },
      { code: "9-12.LS1.B.1", text: "Develop and use models to communicate the role of mitosis, cellular division, and differentiation in producing and maintaining complex organisms.",
        note: "Major events of the cell cycle include cell growth, DNA replication, preparation for division, separation of chromosomes, and separation of cell contents." },
      { code: "9-12.LS1.C.1", text: "Use a model to demonstrate how photosynthesis transforms light energy into stored chemical energy.",
        note: "Emphasis is on illustrating inputs and outputs of matter and the transfer and transformation of energy in photosynthesis by plants and other photosynthesizing organisms. Examples of models could include diagrams, chemical equations, and conceptual models." },
      { code: "9-12.LS1.C.2", text: "Use a model to demonstrate that cellular respiration is a chemical process whereby the bonds of molecules are broken and the bonds in new compounds are formed resulting in a net transfer of energy.",
        note: "Emphasis is on the conceptual understanding of the inputs and outputs of the process of cellular respiration." },
      { code: "9-12.LS1.C.3", text: "Construct and revise an explanation based on evidence that organic macromolecules are primarily composed of six elements, where carbon, hydrogen, and oxygen atoms may combine with nitrogen, sulfur, and phosphorus to form large carbon-based molecules.",
        note: "Large carbon-based molecules included are proteins, carbohydrates, nucleic acids, and lipids." },
      { code: "9-12.LS2.A.1", text: "Explain how various biotic and abiotic factors affect the carrying capacity and biodiversity of an ecosystem using mathematical and/or computational representations.",
        note: "Examples of biotic factors could include relationships among individuals (e.g., feeding relationships, symbioses, competition) and disease. Examples of abiotic factors could include climate and weather conditions, natural disasters, and availability of resources. Genetic diversity includes within a population and species within an ecosystem. Examples of mathematical comparisons could include graphs, charts, histograms, and population changes gathered from simulations or historical data sets." },
      { code: "9-12.LS2.B.1", text: "Construct and revise an explanation based on evidence that the processes of photosynthesis, chemosynthesis, and aerobic and anaerobic respiration are responsible for the cycling of matter and flow of energy through ecosystems and that environmental conditions restrict which reactions can occur.",
        note: "Examples of environmental conditions can include the availability of sunlight or oxygen." },
      { code: "9-12.LS2.B.2", text: "Communicate the pattern of the cycling of matter and the flow of energy among trophic levels in an ecosystem.",
        note: "Emphasis is on using a model of stored energy in biomass to describe the transfer of energy from one tropic level to another. Emphasis is on atoms and molecules as they move through an ecosystem." },
      { code: "9-12.LS2.B.3", text: "Use a model that illustrates the roles of photosynthesis, cellular respiration, decomposition, and combustion to explain the cycling of carbon in its various forms among the biosphere, atmosphere, hydrosphere, and geosphere.",
        note: "The primary forms of carbon include carbon dioxide, hydrocarbons, waste, and biomass. Examples of models could include simulations and mathematical and conceptual models." },
      { code: "9-12.LS2.C.1", text: "Evaluate the claims, evidence, and reasoning that the interactions in ecosystems maintain relatively consistent populations of species while conditions remain stable, but changing conditions may result in new ecosystem dynamics.",
        note: "Examples of changes in ecosystem conditions could include modest biological or physical changes, such as moderate hunting or a seasonal flood; and extreme changes, such as volcanic eruption or sea level rise." },
      { code: "9-12.LS2.C.2", text: "Design, evaluate, and/or refine solutions that positively impact the environment and biodiversity.",
        note: "Examples of solutions may include captive breeding programs, habitat restoration, pollution mitigation, energy conservation, agriculture and mining programs, and ecotourism." },
      { code: "9-12.LS3.A.1", text: "Develop and use models to clarify relationships about how DNA in the form of chromosomes is passed from parents to offspring through the processes of meiosis and fertilization in sexual reproduction.",
        note: "" },
      { code: "9-12.LS3.B.1", text: "Compare and contrast asexual and sexual reproduction with regard to genetic information and variation in offspring.",
        note: "" },
      { code: "9-12.LS3.B.2", text: "Develop and use a model to describe why structural changes to genes (mutations) located on chromosomes may affect proteins and may result in harmful, beneficial, or neutral effects to the structure and function of the organism.",
        note: "Emphasis is on conceptual understanding that changes in genetic material may result in making different proteins." },
      { code: "9-12.LS3.B.3", text: "Make and defend a claim that inheritable genetic variations may result from: (1) new genetic combinations through meiosis, (2) mutations occurring during replication, and/or (3) mutations caused by environmental factors.",
        note: "Emphasis is on using data to support arguments for the way variation occurs." },
      { code: "9-12.LS3.B.4", text: "Apply concepts of statistics and probability to explain the variation and distribution of expressed traits in a population.",
        note: "Emphasis is on the use of mathematics (Punnett Squares) to describe the probability of traits as it relates to genetic and environmental factors in the expression of traits." },
      { code: "9-12.LS4.A.1", text: "Communicate scientific information that common ancestry and biological evolution are supported by multiple lines of empirical evidence.",
        note: "Emphasis is on a conceptual understanding of the role each line of evidence has relating to common ancestry and biological evolution. Examples of evidence could include similarities in DNA sequences, anatomical structures, and order of appearance of structures in embryological development. Communicate could mean written report, oral discussion, etc." },
      { code: "9-12.LS4.A.2", text: "Analyze displays of pictorial data to compare patterns of similarities in the embryological development across multiple species to identify relationships not evident in the fully formed anatomy.",
        note: "Emphasis is on inferring general patterns of relatedness among embryos of different organisms by comparing the macroscopic appearance of diagrams or pictures." },
      { code: "9-12.LS4.B.1", text: "Construct an explanation based on evidence that the process of evolution primarily results from four factors: (1) the potential for a species to increase in number, (2) the heritable genetic variation of individuals in a species due to mutation and sexual reproduction, (3) competition for limited resources, and (4) the proliferation of those organisms that are better able to survive and reproduce in the environment.",
        note: "Emphasis is on using evidence to explain the influence each of the four factors has on number of organisms, behaviors, morphology, or physiology in terms of ability to compete for limited resources and subsequent survival of individuals and adaptation of species. Examples of evidence could include mathematical models such as simple distribution graphs and proportional reasoning." },
      { code: "9-12.LS4.B.2", text: "Apply concepts of statistics and probability to support explanations that organisms with an advantageous heritable trait tend to increase in proportion to organisms lacking this trait.",
        note: "Emphasis is on analyzing shifts in numerical distribution of traits and using these shifts as evidence to support explanations." },
      { code: "9-12.LS4.C.1", text: "Construct an explanation based on evidence for how natural selection leads to adaptation of populations.",
        note: "Emphasis is on using data to provide evidence for how specific biotic and abiotic differences in ecosystems (such as ranges of seasonal temperature, long-term climate change, acidity, light, geographic barriers, or evolution of other organisms) contribute to a change in gene frequency over time, leading to adaptation of populations." },
      { code: "9-12.LS4.C.2", text: "Evaluate the evidence supporting claims that changes in environmental conditions may result in: (1) increases in the number of individuals of some species, (2) the emergence of new species over time, and (3) the extinction of other species.",
        note: "Emphasis is on determining cause and effect relationships for how changes to the environment such as deforestation, fishing, and application of fertilizers, droughts, flood, and the rate of change of the environment affect distribution or disappearance of traits in species." },
      { code: "9-12.LS4.C.3", text: "Create or revise a model to test a solution to mitigate adverse impacts of human activity on biodiversity.",
        note: "Emphasis is on designing solutions for a proposed problem related to threatened or endangered species, or to genetic variation of organisms for multiple species." },
    ],
  },
  {
    id: "mo-sci-9-12-ess",
    label: "Missouri Learning Standards · Science 9-12 · Earth & Space",
    short: "MLS",
    blurb: "Missouri's high school earth and space science expectations: the universe (ESS1), Earth's systems (ESS2), Earth and human activity (ESS3).",
    source: "https://dese.mo.gov/media/pdf/curr-mls-standards-sci-6-12-sboe-2016",
    standards: [
      { code: "9-12.ESS1.A.1", text: "Develop a model based on evidence to illustrate the life span of the sun and the role of nuclear fusion in the Sun's core to release energy in the form of radiation.",
        note: "Emphasis is on the energy transfer mechanisms that allow energy from nuclear fusion in the Sun's core to reach Earth. Examples of evidence for the model include observations of the masses and lifetimes of other stars, as well as the ways that the Sun's radiation varies due to sudden solar flares (\"space weather\")." },
      { code: "9-12.ESS1.A.2", text: "Construct an explanation of the Big Bang theory based on astronomical evidence of light spectra, motion of distant galaxies, and composition of matter in the universe.",
        note: "Emphasis is on the astronomical evidence of the red shift of light from galaxies as an indication that the universe is currently expanding, the cosmic microwave background as the remnant radiation from the Big Bang, and the observed composition of ordinary matter of the universe, primarily found in stars and interstellar gases (from the spectra of electromagnetic radiation from stars), which matches that predicted by the Big Bang theory (3/4 hydrogen and 1/4 helium)." },
      { code: "9-12.ESS1.A.3", text: "Communicate scientific ideas about the way stars, over their life cycle, produce elements.",
        note: "Emphasis is on the way nucleosynthesis, and therefore the different elements created, varies as a function of the mass of a star and the stage of its lifetime." },
      { code: "9-12.ESS1.B.1", text: "Use Kepler's Law to predict the motion of orbiting objects in the solar system.",
        note: "Emphasis is on Newtonian gravitational laws governing orbital motions, which apply to human- made satellites as well as planets and moons." },
      { code: "9-12.ESS1.C.1", text: "Evaluate evidence of the past and current movements of continental and oceanic crust, the theory of plate tectonics, and relative densities of oceanic and continental rocks to explain why continental rocks are generally much older than rocks of the ocean floor.",
        note: "Examples include the ages of oceanic crust increasing with distance from mid-ocean ridges (a result of plate spreading) and the ages of North American continental crust increasing with distance away from a central ancient core (a result of past plate interactions)." },
      { code: "9-12.ESS1.C.2", text: "Apply scientific reasoning and evidence from ancient Earth materials, meteorites, and other planetary surfaces to construct an account of Earth's formation and early history.",
        note: "Emphasis is on using available evidence within the solar system to reconstruct the early history of Earth, which formed along with the rest of the solar system 4.6 billion years ago. Examples of evidence include the absolute ages of ancient materials (obtained by radiometric dating of meteorites, moon rocks, and Earth's oldest minerals), the sizes and compositions of solar system objects, and the impact cratering record of planetary surfaces." },
      { code: "9-12.ESS2.A.1", text: "Develop a model to illustrate how Earth's interior and surface processes (constructive and destructive) operate at different spatial and temporal scales to form continental and ocean-floor features.",
        note: "Emphasis is on how the appearance of land features (such as mountains, valleys, and plateaus) and sea-floor features (such as trenches, ridges, and seamounts) are a result of both constructive forces (such as volcanism, tectonic uplift, and orogeny) and destructive mechanisms (such as weathering, mass wasting, and coastal erosion)." },
      { code: "9-12.ESS2.A.2", text: "Analyze geoscientific data to make the claim that one change to Earth's surface can create changes to other Earth systems.",
        note: "" },
      { code: "9-12.ESS2.A.3", text: "Develop a model based on evidence of Earth's interior to describe the cycling of matter by thermal convection.",
        note: "Emphasis is on both a one-dimensional model of Earth, with radial layers determined by density, and a three-dimensional model, which is controlled by mantle convection and the resulting plate tectonics. Examples of evidence include maps of Earth's three- dimensional structure obtained from seismic waves, records of the rate of change of Earth's magnetic field (as constraints on convection in the outer core), and identification of the composition of Earth's layers from high-pressure laboratory experiments." },
      { code: "9-12.ESS2.A.4", text: "Use a model to describe how variations in the flow of energy into and out of Earth's systems result in changes in climate.",
        note: "" },
      { code: "9-12.ESS2.C.1", text: "Plan and conduct an investigation of the properties of water and its effects on Earth materials and surface processes.",
        note: "Emphasis is on mechanical and chemical investigations with water and a variety of solid materials to provide the evidence for connections between the hydrologic cycle and system interactions commonly known as the rock cycle. Examples of mechanical investigations include stream transportation and deposition using a stream table, erosion using variations in soil moisture content, or ice wedging by the expansion of water as it freezes. Examples of chemical investigations include chemical weathering and recrystallization (by testing the solubility of different materials) or melt generation (by examining how water lowers the melting temperature of most solids)." },
      { code: "9-12.ESS2.D.1", text: "Develop a quantitative model to describe the cycling of carbon among the hydrosphere, atmosphere, geosphere, and biosphere.",
        note: "Emphasis is on modeling biogeochemical cycles that include the cycling of carbon through the ocean, atmosphere, soil, and biosphere (including humans), providing the foundation for living organisms." },
      { code: "9-12.ESS3.A.1", text: "Construct an explanation based on evidence for how the availability of natural resources, occurrence of natural hazards, and changes in climate have influenced human activity.",
        note: "Examples of key natural resources include access to fresh water, regions of fertile soils such as river deltas, and high concentrations of minerals and fossil fuels. Examples of natural hazards can be from interior processes (such as volcanic eruptions and earthquakes), surface processes (such as tsunamis, mass wasting and soil erosion), and severe weather. Examples of the results of changes in climate that can affect populations or drive mass migrations include changes to sea level, regional patterns of temperature and precipitation, and the types of crops and livestock that can be raised." },
      { code: "9-12.ESS3.A.2", text: "Evaluate competing design solutions for developing, managing, and utilizing energy and mineral resources based on economic, social, and environmental cost-benefit ratios.",
        note: "Emphasis is on the conservation, recycling, and reuse of resources (such as minerals and metals) where possible, and on minimizing impacts where it is not. Examples include developing best practices for agricultural soil use, mining (for coal, tar sands, and oil shale), and pumping (for petroleum and natural gas). Science knowledge indicates what can happen in natural systems-not what should happen." },
      { code: "9-12.ESS3.C.1", text: "Create a computational simulation to illustrate the relationships among management of natural resources, the sustainability of human populations, and biodiversity.",
        note: "Examples of factors that affect the management of natural resources include costs of resource extraction and waste management, per-capita consumption, and the development of new technologies. Examples of factors that affect human sustainability include agricultural efficiency, levels of conservation, and urban planning." },
      { code: "9-12.ESS3.C.2", text: "Evaluate or refine a technological solution that reduces impacts of human activities on natural systems in order to restore stability and or biodiversity of the ecosystem as well as prevent their reoccurrences.",
        note: "Examples of human activities could include forest fires, acid rain, flooding, urban development, pollution, deforestation, and introduction of an invasive species." },
      { code: "9-12.ESS3.D.1", text: "Analyze geoscientific data and the results from global climate models to make an evidence-based forecast of the current rate of global or regional climate change and associated future impacts to Earth systems.",
        note: "Examples of evidence, for both data and climate model outputs, are for climate changes (such as precipitation and temperature) and their associated impacts (such as on sea level, glacial ice volumes, or atmosphere and ocean composition)." },
      { code: "9-12.ESS3.D.2", text: "Predict how human activity affects the relationships between Earth systems in both positive and negative ways.",
        note: "Examples of Earth systems to be considered are the hydrosphere, atmosphere, cryosphere, geosphere, and/or biosphere." },
    ],
  },
  {
    id: "mo-sci-9-12-ets",
    label: "Missouri Learning Standards · Science 9-12 · Engineering Design",
    short: "MLS",
    blurb: "Missouri's four high school engineering design expectations (ETS1), for any science course that runs a design project.",
    source: "https://dese.mo.gov/media/pdf/curr-mls-standards-sci-6-12-sboe-2016",
    standards: [
      { code: "9-12.ETS1.A.1", text: "Analyze a major global challenge to specify qualitative and quantitative criteria and constraints for solutions that account for societal needs and wants.",
        note: "" },
      { code: "9-12.ETS1.A.2", text: "Design a solution to a complex real-world problem by breaking it down into smaller, more manageable problems that can be solved through engineering.",
        note: "" },
      { code: "9-12.ETS1.B.1", text: "Evaluate a solution to a complex real-world problem based on prioritized criteria and trade-offs that account for a range of constraints, including cost, safety, reliability, and aesthetics as well as possible social, cultural, and environmental impacts.",
        note: "" },
      { code: "9-12.ETS1.B.2", text: "Use a computer simulation to model the impact of proposed solutions to a complex real-world problem with numerous criteria and constraints on interactions within and between systems relevant to the problem.",
        note: "" },
    ],
  },
  {
    id: "mo-sci-6-8",
    label: "Missouri Learning Standards · Science 6-8",
    short: "MLS",
    blurb: "Every middle school science expectation, all four strands: physical, life, earth and space, and engineering design.",
    source: "https://dese.mo.gov/media/pdf/curr-mls-standards-sci-6-12-sboe-2016",
    standards: [
      { code: "6-8.ESS1.A.1", text: "Develop and use a model of the Earth-sun-moon system to explain the cyclic patterns of lunar phases and eclipses of the sun and moon.",
        note: "Examples of models can be physical, graphical, or conceptual and should emphasize relative positions and distances." },
      { code: "6-8.ESS1.A.2", text: "Develop and use a model of the Earth-sun system to explain the cyclical pattern of seasons, which includes the Earth's tilt and directional angle of sunlight on different areas of Earth across the year.",
        note: "Examples of models can be physical, graphical, or conceptual." },
      { code: "6-8.ESS1.A.3", text: "Develop and use a model to describe the role of gravity in the motions within galaxies and the solar system.",
        note: "Emphasis for the model is on gravity as the force that holds together the solar system and Milky Way galaxy and controls orbital motions within them. Examples of models can be physical or conceptual." },
      { code: "6-8.ESS1.B.1", text: "Analyze and interpret data to determine scale properties of objects in the solar system.",
        note: "Examples of scale properties include the sizes of an object's layers (such as crust and atmosphere), surface features (such as volcanoes), and orbital radius. Examples of data include statistical information, drawings and photographs, and models." },
      { code: "6-8.ESS1.C.1", text: "Construct a scientific explanation based on evidence from rock strata for how the geologic time scale is used to organize Earth's history.",
        note: "Emphasis is on how analyses of rock formations and the fossils they contain are used to establish relative ages of major events in Earth's history. Examples of Earth's major events could range from being very recent (such as the last Ice Age or the earliest fossils of homo sapiens) to very old (such as the formation of Earth or the earliest evidence of life). Examples can include the formation of mountain chains and ocean basins, the evolution or extinction of particular living organisms, or significant volcanic eruptions." },
      { code: "6-8.ESS2.A.1", text: "Develop and use a model to illustrate that energy from the Earth's interior drives convection which cycles Earth's crust leading to melting, crystallization, weathering and deformation of large rock formations, including generation of ocean sea floor at ridges, submergence of ocean sea floor at trenches, mountain building and active volcanic chains.",
        note: "The emphasis is on large-scale cycling resulting from plate tectonics that includes changes in rock types through erosion, heat and pressure." },
      { code: "6-8.ESS2.A.2", text: "Construct an explanation based on evidence for how geoscience processes have changed Earth's surface at varying time and spatial scales.",
        note: "Emphasis is on how processes change Earth's surface at time and spatial scales that can be large (such as slow plate motions or the uplift of large mountain ranges) or small (such as rapid landslides or microscopic geochemical reactions), and how many geoscience processes (such as earthquakes, volcanoes, and meteor impacts) usually behave gradually but are punctuated by catastrophic events. Examples of geoscience processes include surface weathering and deposition by the movements of water, ice, and wind. Emphasis is on geoscience processes that shape local geographic features, where appropriate." },
      { code: "6-8.ESS2.B.1", text: "Analyze and interpret data on the distribution of fossils and rocks, continental shapes, and seafloor structures to provide evidence of the past plate motions.",
        note: "Examples of data include similarities of rock and fossil types on different continents, the shapes of the continents (including continental shelves), and the locations of ocean structures (such as ridges, fracture zones, and trenches)." },
      { code: "6-8.ESS2.C.1", text: "Design and develop a model to describe the cycling of water through Earth's systems driven by energy from the sun and the force of gravity.",
        note: "Emphasis is on the ways water changes its state as it moves through the multiple pathways of the hydrologic cycle. Examples of models can be conceptual or physical." },
      { code: "6-8.ESS2.C.2", text: "Research, collect, and analyze data to provide evidence for how the motions and complex interactions of air masses results in changes in weather conditions.",
        note: "Emphasis is on how air masses flow from regions of high pressure to low pressure, causing weather (defined by temperature, pressure, humidity, precipitation, and wind) at a fixed location to change over time, and how sudden changes in weather can result when different air masses collide. Emphasis is on how weather can be predicted within possible ranges. Examples of data can be provided to students (such as weather maps, diagrams, and visualizations) or obtained through laboratory experiments (such as with condensation)." },
      { code: "6-8.ESS2.C.3", text: "Develop and use a model to describe how unequal heating and rotation of the Earth cause patterns of atmospheric and oceanic circulation that determine regional climates.",
        note: "Emphasis is on how patterns vary by latitude, altitude, and geographic land distribution. Emphasis of atmospheric circulation is on the sunlight-driven latitudinal banding, the Coriolis effect, and resulting prevailing winds; emphasis of ocean circulation is on the transfer of heat by the global ocean convection cycle, which is constrained by the Coriolis effect and the outlines of continents. Examples of models can be diagrams, maps and globes, or digital representations." },
      { code: "6-8.ESS3.A.1", text: "Construct a scientific explanation based on evidence for how the uneven distributions of Earth's mineral, energy, and groundwater resources are the result of past and current geoscience processes and human activity.",
        note: "Emphasis is on how these resources are limited and typically non-renewable, and how their distributions are significantly changing as a result of removal by humans. Examples of uneven distributions of resources as a result of past processes include but are not limited to petroleum (locations of the burial of organic marine sediments and subsequent geologic traps), metal ores (locations of past volcanic and hydrothermal activity associated with subduction zones), and soil (locations of active weathering and/or deposition of rock)." },
      { code: "6-8.ESS3.B.1", text: "Analyze and interpret data on natural hazards to forecast future catastrophic events and inform the development of technologies to mitigate their effects.",
        note: "Emphasis is on how some natural hazards, such as volcanic eruptions and severe weather, are preceded by phenomena that allow for reliable predictions, but others, such as earthquakes, occur suddenly and with no notice, and thus are not yet predictable. Examples of natural hazards can be taken from interior processes (such as earthquakes and volcanic eruptions), surface processes (such as mass wasting and tsunamis), or severe weather events (such as hurricanes, tornadoes, and floods). Examples of data can include the locations, magnitudes, and frequencies of the natural hazards. Examples of technologies can be global (such as satellite systems to monitor hurricanes or forest fires) or local (such as building basements in tornado-prone regions or reservoirs to mitigate droughts)." },
      { code: "6-8.ESS3.C.1", text: "Analyze data to define the relationship for how increases in human population and per-capita consumption of natural resources impact Earth's systems.",
        note: "Examples of data include grade-appropriate databases on human populations and the rates of consumption of food and natural resources (such as freshwater, mineral, and energy). Examples of impacts can include changes to the appearance, composition, and structure of Earth's systems as well as the rates at which they change." },
      { code: "6-8.ESS3.C.2", text: "Apply scientific principles to design a method for monitoring and minimizing a human impact on the environment.",
        note: "Examples of the design process include examining human environmental impacts, assessing the kinds of solutions that are feasible, and designing and evaluating solutions that could reduce that impact. Examples of human impacts can include water usage (such as the withdrawal of water from streams and aquifers or the construction of dams and levees), land usage (such as urban development, agriculture, or the removal of wetlands), and pollution (such as of the air, water, or land)." },
      { code: "6-8.ESS3.D.1", text: "Analyze evidence of the factors that have caused the change in global temperatures over the past century.",
        note: "Examples of factors include human activities (such as fossil fuel combustion, cement production, and agricultural activity) and natural processes (such as changes in incoming solar radiation or volcanic activity). Examples of evidence can include tables, graphs, and maps of global and regional temperatures, atmospheric levels of gases such as carbon dioxide and methane, and the rates of human activities." },
      { code: "6-8.ETS1.A.1", text: "Define the criteria and constraints of a design problem with sufficient precision to ensure a successful solution, taking into account relevant scientific principles and potential impacts on people and the natural environment that may limit possible solutions.",
        note: "" },
      { code: "6-8.ETS1.B.1", text: "Evaluate competing design solutions using a systematic process to determine how well they meet the criteria and constraints of the problem.",
        note: "" },
      { code: "6-8.ETS1.B.2", text: "Analyze data from tests to determine similarities and differences among several design solutions to identify the best characteristics of each that can be combined into a new solution to better meet the criteria for success.",
        note: "" },
      { code: "6-8.ETS1.B.3", text: "Develop a model to generate data for iterative testing and modification of a proposed object, tool, or process such that an optimal design can be achieved.",
        note: "" },
      { code: "6-8.LS1.A.1", text: "Provide evidence that organisms (unicellular and multicellular) are made of cells and that a single cell must carry out all of the basic functions of life.",
        note: "Emphasis is on developing evidence that living things are made of cells, distinguishing between living and non-living things, and understanding that living things may be made of one cell or many and varied cells." },
      { code: "6-8.LS1.A.2", text: "Develop and use a model to describe the function of a cell as a whole and ways parts of the cells contribute to that function.",
        note: "Emphasis is on the cell functioning as a whole system and the primary role of identified parts of the cell, specifically the nucleus, chloroplasts, mitochondria, cell membrane, and cell wall." },
      { code: "6-8.LS1.A.3", text: "Develop an argument supported by evidence for how multicellular organisms are organized by varying levels of complexity; cells, tissue, organs, organ systems.",
        note: "" },
      { code: "6-8.LS1.A.4", text: "Present evidence that body systems interact to carry out key body functions, including providing nutrients and oxygen to cells, removing carbon dioxide and waste from cells and the body, controlling body motion/activity and coordination, and protecting the body.",
        note: "" },
      { code: "6-8.LS1.B.1", text: "Construct an explanation for how characteristic animal behaviors as well as specialized plant structures affect the probability of successful reproduction of animals and plants respectively.",
        note: "Examples of animal behaviors that affect the probability of animal reproduction could include nest building to protect young from cold, herding of animals to protect young from predators, and vocalization of animals and colorful plumage to attract mates for breeding. Examples of animal behaviors that affect the probability of plant reproduction could include transferring pollen or seeds; and, creating conditions for seed germination and growth. Examples of plant structures that affect the probability of plant reproduction could include bright flowers attracting butterflies that transfer pollen, flower nectar and odors that attract insects that transfer pollen, and hard shells on nuts that squirrels bury." },
      { code: "6-8.LS1.B.2", text: "Construct a scientific explanation based on evidence for how environmental and genetic factors influence the growth of organisms.",
        note: "Examples of local environmental conditions could include availability of food, light, space, and water. Examples of genetic factors could include large breed cattle and species of grass affecting growth of organisms. Examples of evidence could include drought decreasing plant growth, fertilizer increasing plant growth, different varieties of plant seeds growing at different rates in different conditions, and fish growing larger in large ponds than they do in small ponds." },
      { code: "6-8.LS1.C.1", text: "Construct a scientific explanation based on evidence for the role of photosynthesis and cellular respiration in the cycling of matter and flow of energy into and out of organisms.",
        note: "" },
      { code: "6-8.LS2.A.1", text: "Analyze and interpret data to provide evidence for the effects of resource availability on individual organisms and populations of organisms in an ecosystem.",
        note: "Emphasis is on cause and effect relationships between resources and growth of individual organisms and the numbers of organisms in ecosystems during periods of abundant and scarce resources." },
      { code: "6-8.LS2.A.2", text: "Construct an explanation that predicts the patterns of interactions among and between the biotic and abiotic factors in a given ecosystem.",
        note: "Relationships may include competition, predation, and symbiosis." },
      { code: "6-8.LS2.B.1", text: "Develop a model to describe the cycling of matter and flow of energy among living and nonliving parts of an ecosystem.",
        note: "Emphasis is on describing the conservation of matter and flow of energy into and out of various ecosystems, including food chains and food webs." },
      { code: "6-8.LS2.C.1", text: "Construct an argument supported by empirical evidence that explains how changes to physical or biological components of an ecosystem affect populations.",
        note: "Emphasis is on recognizing patterns in data and making inferences about changes in populations, defining the boundaries of the system, and on evaluating empirical evidence supporting arguments about changes to ecosystems." },
      { code: "6-8.LS2.C.2", text: "Evaluate benefits and limitations of differing design solutions for maintaining an ecosystem.",
        note: "Examples of design solutions could include water, land, and species protection, and the prevention of soil erosion. Examples of design solution constraints could include scientific, economic, and social considerations." },
      { code: "6-8.LS4.A.1", text: "Analyze and interpret evidence from the fossil record to infer patterns of environmental change resulting in extinction and changes to life forms throughout the history of the Earth.",
        note: "Examples of evidence include sets of fossils that indicate an environment, anatomical structures that indicate the function of an organism in the environment, and fossilized tracks that indicate behavior of organisms." },
      { code: "6-8.LS4.B.1", text: "Construct an explanation based on evidence that describes how genetic variations of traits in a population increase some individuals' probability of surviving and reproducing in a specific environment.",
        note: "Emphasis is on using simple probability statements and proportional reasoning to construct explanations." },
      { code: "6-8.LS4.B.2", text: "Gather and synthesize information about the technologies that have changed the way humans influence the inheritance of desired traits in organisms.",
        note: "Emphasis is on synthesizing information from reliable sources about the influence of humans on genetic outcomes in artificial selection (such as genetic modification, animal husbandry, and farming practices)." },
      { code: "6-8.LS4.C.1", text: "Interpret graphical representations to support explanations of how natural selection may lead to increases and decreases of specific traits in populations over time.",
        note: "" },
      { code: "6-8.PS1.A.1", text: "Develop models to describe the atomic composition of simple molecules and extended structures.",
        note: "Emphasis is on developing models of molecules that vary in complexity. Examples of simple molecules could include ammonia and methanol. Examples of extended structures could include sodium chloride or diamonds. Examples of molecular-level models could include drawings, 3D ball and stick structures, or computer representations showing different molecules with different types of atoms." },
      { code: "6-8.PS1.A.2", text: "Analyze and interpret data on the properties of substances before and after the substances interact to determine if a chemical reaction has occurred.",
        note: "Examples of reactions could include burning sugar or steel wool, fat reacting with sodium hydroxide, and mixing zinc with hydrogen chloride." },
      { code: "6-8.PS1.A.3", text: "Gather, analyze, and present information to describe that synthetic materials come from natural resources and how they impact society.",
        note: "Emphasis is on natural resources that undergo a chemical process to form the synthetic material. Examples of new materials could include new medicine, foods, and alternative fuels." },
      { code: "6-8.PS1.A.4", text: "Develop a model that describes changes in particle motion, temperature, and state of a pure substance when thermal energy is added or removed.",
        note: "Emphasis is on qualitative molecular- level models of solids, liquids, and gases to show that adding or removing thermal energy increases or decreases kinetic energy of the particles until a change of state occurs. Examples of models could include drawings and diagrams. Examples of particles could include molecules or inert atoms. Examples of pure substances could include water, carbon dioxide, and helium." },
      { code: "6-8.PS1.B.1", text: "Develop and use a model to describe how the total number of atoms remains the same during a chemical reaction and thus mass is conserved.",
        note: "Emphasis is on law of conservation of matter and on physical models or drawings, including digital forms that represent atoms." },
      { code: "6-8.PS1.B.2", text: "Construct, test, and modify a device that either releases or absorbs thermal energy by chemical processes.",
        note: "Emphasis is on the design, controlling the transfer of energy to the environment, and modification of a device using factors such as type and concentration of a substance. Examples of designs could involve chemical reactions such as dissolving ammonium chloride or calcium chloride." },
      { code: "6-8.PS2.A.1", text: "Apply physics principles to design a solution that minimizes the force of an object during a collision and develop an evaluation of the solution.",
        note: "" },
      { code: "6-8.PS2.A.2", text: "Plan and conduct an investigation to provide evidence that the change in an object's motion depends on the sum of the forces on the object and the mass of the object.",
        note: "Emphasis is on balanced (Newton's First Law) and unbalanced forces in a system, qualitative comparisons of forces, mass and changes in motion (Newton's Second Law), frame of reference, and specification of units." },
      { code: "6-8.PS2.B.1", text: "Analyze diagrams and collect data to determine the factors that affect the strength of electric and magnetic forces.",
        note: "Examples of devices that use electric and magnetic forces could include electromagnets, electric motors, or generators. Examples of data could include the effect of the number of turns of wire on the strength of an electromagnet, or the effect of increasing the number or strength of magnets on the speed of an electric motor." },
      { code: "6-8.PS2.B.2", text: "Create and analyze a graph to use as evidence to support the claim that gravitational interactions depend on the mass of interacting objects.",
        note: "Examples of evidence for arguments could include data generated from simulations or digital tools; and charts displaying mass, strength of interaction, distance from the sun, and orbital periods of objects within the solar system." },
      { code: "6-8.PS2.B.3", text: "Conduct an investigation and evaluate the experimental design to provide evidence that electric and magnetic fields exist between objects exerting forces on each other even though the objects are not in contact.",
        note: "Examples of this phenomenon could include the interactions of magnets, electrically- charged strips of tape, and electrically-charged pith balls. Examples of investigations could include first-hand experiences or simulations." },
      { code: "6-8.PS3.A.1", text: "Construct and interpret graphical displays of data to describe the relationships of kinetic energy to the mass of an object and to the speed of an object.",
        note: "Emphasis is on descriptive relationships between kinetic energy and mass separately from kinetic energy and speed. Examples could include riding a bicycle at different speeds, rolling different sizes of rocks downhill, and getting hit by a whiffle ball versus a tennis ball." },
      { code: "6-8.PS3.A.2", text: "Develop a model to describe that when the arrangement of objects interacting at a distance changes, different amounts of potential energy are stored in the system.",
        note: "Emphasis is on relative amounts of potential energy, not on calculations of potential energy. Examples of objects within systems interacting at varying distances could include: the Earth and either a roller coaster cart at varying positions on a hill or objects at varying heights on shelves, changing the direction/orientation of a magnet, and a balloon with static electrical charge being brought closer to a classmate's hair. Examples of models could include representations, diagrams, pictures, and written descriptions of systems." },
      { code: "6-8.PS3.A.3", text: "Apply scientific principles to design, construct, and test a device that either minimizes or maximizes thermal energy transfer.",
        note: "Examples of devices could include an insulated box, a solar cooker, and a Styrofoam cup." },
      { code: "6-8.PS3.A.4", text: "Plan and conduct an investigation to determine the relationships among the energy transferred, the type of matter, the mass, and the change in the temperature of the sample.",
        note: "Examples of experiments could include comparing final water temperatures after different masses of ice melted in the same volume of water with the same initial temperature, the temperature change of samples of different materials with the same mass as they cool or heat in the environment, or the same material with different masses when a specific amount of energy is added." },
      { code: "6-8.PS3.B.1", text: "Construct, use, and present arguments to support the claim that when the kinetic energy of an object changes, energy is transferred to or from the object.",
        note: "Examples of empirical evidence used in arguments could include an inventory or other representation of the energy before and after the transfer in the form of temperature changes or motion of object." },
      { code: "6-8.PS4.A.1", text: "Use mathematical representations to describe a simple model for waves that includes how the amplitude of a wave is related to the energy in a wave.",
        note: "Emphasis is on describing waves with both qualitative and quantitative thinking." },
      { code: "6-8.PS4.A.2", text: "Develop and use a model to describe that waves are reflected, absorbed, or transmitted through various materials.",
        note: "Emphasis is on both light and mechanical waves. Examples of models could include drawings, simulations, and written descriptions." },
    ],
  },
];
